const swaggerJsDoc=require('swagger-jsdoc');
const options={
    //List of files to be processed
    apis:['./routes/auth.js'],
    basePath:'/',
    swaggerDefinition:{
        info:{
            description: 'Test API with autogenerated swagger doc',
            swagger: '2.0',
            title: 'Test API',
            version: '1.0.0',
        }
    }
};

const specs=swaggerJsDoc(options);
//export default specs;
module.exports=specs;